import { useCallback, useEffect, useRef, useState } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { ContactShadows } from '@react-three/drei';
import * as THREE from 'three';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import Eyebrow from '../ui/Eyebrow';
import TShirtGLB from './models/TShirtGLB';
import Badge from './models/Badge';
import Cap from './models/Cap';
import { money } from '../../data/merch-catalog';

/*
 * Store showcase hero — a rigid, single-product display. One product at a
 * time sits on the pedestal, slowly rotating; drag rotates it (with
 * momentum), swipe switches drops. No turntable, no orbiting, no sparkle.
 * The canvas only mounts while the hero is on screen, so the GPU is idle
 * everywhere else.
 */

const SCENES = [
  {
    id: 'tee',
    kicker: 'Drop 01 · Tees',
    title: <>The Zone 7 <span>tee.</span></>,
    sub: 'Heavyweight cotton with the Z7 lockup up front. On the mannequin, on you, on everyone.',
    spec: 'Heavyweight cotton · Unisex fit',
    price: money(800),
    cta: 'Shop tees',
    href: '#tees',
    accent: '#E11A6E'
  },
  {
    id: 'badge',
    kicker: 'Drop 02 · Badges & Pins',
    title: <>Pin the <span>badge.</span></>,
    sub: 'Gold-rimmed enamel with the Zone 7 crest — for blazers, bags and bragging rights.',
    spec: 'Gold-rimmed enamel · Clutch back',
    price: money(250),
    cta: 'Shop badges & pins',
    href: '#badges',
    accent: '#F2A900'
  },
  {
    id: 'cap',
    kicker: 'Drop 03 · Caps',
    title: <>Cap the <span>look.</span></>,
    sub: 'Structured five-panel with an embroidered Z7 front. One size, everyone welcome.',
    spec: 'Structured 5-panel · One size',
    price: money(600),
    cta: 'Shop caps',
    href: '#caps',
    accent: '#0E7490'
  }
];

const mod = (n, m) => ((n % m) + m) % m;

function Pedestal() {
  return (
    <group>
      <mesh position={[0, -1.06, 0]}>
        <cylinderGeometry args={[1.85, 2.02, 0.2, 72]} />
        <meshStandardMaterial color="#131019" roughness={0.38} metalness={0.28} />
      </mesh>
      <mesh position={[0, -0.955, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <torusGeometry args={[1.85, 0.014, 10, 90]} />
        <meshStandardMaterial color="#F2A900" roughness={0.3} metalness={0.85} />
      </mesh>
      <ContactShadows position={[0, -1.02, 0]} opacity={0.42} scale={13} blur={2.6} far={3.4} />
    </group>
  );
}

/*
 * Procedural studio environment — reflections for every material without a
 * single network request. RoomEnvironment is generated by three.js itself.
 */
function StudioEnv() {
  const gl = useThree((s) => s.gl);
  const scene = useThree((s) => s.scene);

  useEffect(() => {
    const pmrem = new THREE.PMREMGenerator(gl);
    const envTex = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
    scene.environment = envTex;
    scene.environmentIntensity = 0.6;
    return () => {
      scene.environment = null;
      envTex.dispose();
      pmrem.dispose();
    };
  }, [gl, scene]);

  return null;
}

/*
 * Fits the product inside the frame at every aspect ratio — wide desktop
 * frames show the product large; narrow mobile frames zoom the camera out
 * so sleeves and brims never clip the edges.
 */
function ResponsiveZoom() {
  const camera = useThree((s) => s.camera);
  const size = useThree((s) => s.size);

  useEffect(() => {
    const aspect = size.width / size.height;
    camera.zoom = aspect < 0.85 ? 0.58 : aspect < 1.15 ? 0.8 : 1;
    camera.updateProjectionMatrix();
  }, [camera, size]);

  return null;
}

function ShowcaseRig({ rot, children }) {
  const group = useRef(null);

  useFrame((_, delta) => {
    const g = group.current;
    if (!g) return;
    const r = rot.current;
    if (r.dragging) {
      g.rotation.y = r.y;
      return;
    }
    // momentum decay → idle auto-rotate
    r.y += r.vel;
    r.vel *= Math.pow(0.002, delta);
    if (Math.abs(r.vel) < 0.001) r.y += delta * 0.26;
    g.rotation.y = r.y;
  });

  return <group ref={group}>{children}</group>;
}

function StagePointer({ rot, onSwipe, onInteract }) {
  const gl = useThree((s) => s.gl);

  useEffect(() => {
    const el = gl.domElement;
    el.style.touchAction = 'pan-y';
    el.style.cursor = 'grab';
    const r = rot.current;
    let pointerId = null;
    let startX = 0;
    let startY = 0;
    let lastX = 0;

    const down = (e) => {
      if (e.pointerType === 'mouse' && e.button !== 0) return;
      pointerId = e.pointerId;
      startX = lastX = e.clientX;
      startY = e.clientY;
      r.dragging = true;
      r.vel = 0;
      el.setPointerCapture(e.pointerId);
      el.style.cursor = 'grabbing';
      onInteract();
    };

    const move = (e) => {
      if (!r.dragging || e.pointerId !== pointerId) return;
      const dx = e.clientX - lastX;
      lastX = e.clientX;
      r.y += dx * 0.0062;
      r.vel = dx * 0.0062;
    };

    const up = (e) => {
      if (e.pointerId !== pointerId) return;
      pointerId = null;
      r.dragging = false;
      el.style.cursor = 'grab';
      const dx = lastX - startX;
      const dy = e.clientY - startY;
      if (Math.abs(dx) > 64 && Math.abs(dy) < 90) onSwipe(dx > 0 ? -1 : 1);
      onInteract();
    };

    el.addEventListener('pointerdown', down);
    el.addEventListener('pointermove', move);
    el.addEventListener('pointerup', up);
    el.addEventListener('pointercancel', up);
    return () => {
      el.removeEventListener('pointerdown', down);
      el.removeEventListener('pointermove', move);
      el.removeEventListener('pointerup', up);
      el.removeEventListener('pointercancel', up);
    };
  }, [gl, rot, onSwipe, onInteract]);

  return null;
}

function Showcase({ index, rot, onSwipe, onInteract }) {
  return (
    <>
      <fog attach="fog" args={['#0B0914', 11, 17]} />
      <StudioEnv />
      <ResponsiveZoom />
      <hemisphereLight args={['#ffffff', '#191624', 0.4]} />
      <directionalLight position={[3.5, 5, 5]} intensity={0.95} />
      <pointLight position={[-4, 1.6, 2.6]} intensity={14} distance={14} color="#FF5C9D" />
      <pointLight position={[4, -1, 3]} intensity={10} distance={13} color="#F2A900" />
      <pointLight position={[0, 3.4, -7]} intensity={8} distance={14} color="#4C6EF5" />
      <StagePointer rot={rot} onSwipe={onSwipe} onInteract={onInteract} />
      <ShowcaseRig rot={rot}>
        <group scale={1.12}>
          <group visible={index === 0}>
            <TShirtGLB />
          </group>
          <group visible={index === 1} position={[0, 0.45, 0]}>
            <Badge />
          </group>
          <group visible={index === 2}>
            <Cap color="#232A4E" />
          </group>
        </group>
      </ShowcaseRig>
      <Pedestal />
    </>
  );
}

export default function StoreHero() {
  const root = useRef(null);
  const copyRef = useRef(null);
  const hintRef = useRef(null);
  const [index, setIndex] = useState(0);
  const [live, setLive] = useState(false);
  const rot = useRef({ y: 0, vel: 0, dragging: false });

  const scene = SCENES[index];

  const go = useCallback((dir) => {
    setIndex((i) => mod(i + dir, SCENES.length));
    if (hintRef.current) hintRef.current.classList.add('hide');
  }, []);

  const interact = useCallback(() => {
    if (hintRef.current) hintRef.current.classList.add('hide');
  }, []);

  // mount the canvas only while the hero is on screen
  useEffect(() => {
    const el = root.current;
    if (!el) return;
    const io = new IntersectionObserver(
      ([en]) => {
        if (en.isIntersecting) setLive(true);
      },
      { threshold: 0.05 }
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  // slow auto-advance while on screen
  useEffect(() => {
    const el = root.current;
    if (!el) return;
    const io = new IntersectionObserver(([en]) => (el.__visible = en.isIntersecting), { threshold: 0.4 });
    io.observe(el);
    const timer = setInterval(() => {
      if (el.__visible && !document.hidden) setIndex((i) => (i + 1) % SCENES.length);
    }, 9000);
    return () => {
      io.disconnect();
      clearInterval(timer);
    };
  }, []);

  useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'ArrowRight') go(1);
      if (e.key === 'ArrowLeft') go(-1);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [go]);

  const goSection = () => {
    const target = document.querySelector(scene.href);
    if (target) target.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <section className="sh-hero" ref={root} id="top">
      <div className="sh-bg"></div>

      <div className="wrap sh-wrap">
        <div className="sh-copy" ref={copyRef}>
          <Eyebrow dark>Rotaract District 3292 · Official Merch</Eyebrow>
          <div className="sh-panels">
            {SCENES.map((s, i) => (
              <div key={s.id} className={`sh-panel ${i === index ? 'on' : ''}`} aria-hidden={i !== index}>
                <span className="sh-kicker" style={{ color: s.accent }}>
                  {s.kicker}
                </span>
                <h1 className="sh-h1">{s.title}</h1>
                <p className="sh-sub">{s.sub}</p>
                <div className="sh-actions">
                  <span className="sh-price">{s.price}</span>
                  <a
                    className="btn btn-primary"
                    href={s.href}
                    onClick={(e) => {
                      e.preventDefault();
                      goSection();
                    }}
                  >
                    {s.cta} →
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="sh-stage">
          <div className="sh-frame">
            {live ? (
              <Canvas
                camera={{ position: [0, 0.5, 5.0], fov: 34 }}
                dpr={[1, 1.5]}
                gl={{ antialias: true, alpha: true, powerPreference: 'high-performance' }}
                style={{ width: '100%', height: '100%' }}
              >
                <Showcase index={index} rot={rot} onSwipe={go} onInteract={interact} />
              </Canvas>
            ) : (
              <div className="sh-boot" aria-hidden="true">
                <span>Z7</span>
              </div>
            )}
          </div>
          <span className="sh-spec" key={scene.id}>
            {scene.spec}
          </span>
        </div>
      </div>

      <div className="sh-bottom">
        <button type="button" className="sh-arrow" aria-label="Previous drop" onClick={() => go(-1)}>
          ←
        </button>
        <div className="sh-dots">
          {SCENES.map((s, i) => (
            <button
              key={s.id}
              type="button"
              className={`sh-dot ${i === index ? 'on' : ''}`}
              aria-label={s.kicker}
              onClick={() => {
                setIndex(i);
                interact();
              }}
            />
          ))}
        </div>
        <span className="sh-count">
          0{index + 1} / 0{SCENES.length}
        </span>
        <button type="button" className="sh-arrow" aria-label="Next drop" onClick={() => go(1)}>
          →
        </button>
      </div>

      <div className="sh-hint" ref={hintRef} aria-hidden="true">
        ✦ drag to rotate · swipe to switch
      </div>

      <div className="hero-scroll-hint" aria-hidden="true">
        <span className="mouse"><i></i></span> scroll — the drop keeps going
      </div>
    </section>
  );
}
