/* Learn section search index - kept in sync with tutorials.html GUIDES, guides.html STATIC_GUIDES and rkt-quiz.html GUIDES */
window.LEARN_INDEX = [
  { p: "/tutorials", a: "meetings", t: "Running General Meetings", s: "Tutorials", icon: "🧭" },
  { p: "/tutorials", a: "board", t: "Running Board Meetings", s: "Tutorials", icon: "🧭" },
  { p: "/tutorials", a: "assembly", t: "Club Assemblies", s: "Tutorials", icon: "🧭" },
  { p: "/tutorials", a: "zrr", t: "ZRR Visits", s: "Tutorials", icon: "🧭" },
  { p: "/tutorials", a: "drr", t: "DRR Visits", s: "Tutorials", icon: "🧭" },
  { p: "/tutorials", a: "blood", t: "Blood Donation Programs", s: "Tutorials", icon: "🧭" },
  { p: "/tutorials", a: "grants", t: "Grants: Funding Service", s: "District Handbook", icon: "📘" },
  { p: "/tutorials", a: "twinship", t: "Twinship & the MOU", s: "District Handbook", icon: "📘" },
  { p: "/tutorials", a: "newclub", t: "Starting a New Club", s: "District Handbook", icon: "📘" },
  { p: "/tutorials", a: "projects", t: "Projects: 7 Areas of Focus", s: "District Handbook", icon: "📘" },
  { p: "/tutorials", a: "health", t: "The Club Health Checkup", s: "District Handbook", icon: "📘" },
  { p: "/tutorials", a: "leadership", t: "Leadership & Officer Transition", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "recognition", t: "Recognition & Events", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "wellbeing", t: "Wellbeing & Culture", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "finance", t: "Finance & Fundraising", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "makeup", t: "Attendance & Make-Up", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "digital", t: "Digital Tools & Tech", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "execution", t: "Service Project Execution", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "profdev", t: "Professional Development", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "publicimage", t: "Public Image & Communications", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "international", t: "International & Twin Clubs", s: "Officer Playbook", icon: "🛡️" },
  { p: "/tutorials", a: "sponsor", t: "Sponsor Relationship", s: "Officer Playbook", icon: "🛡️" },
  { p: "/guides", t: "Standard Rotaract Club Constitution", s: "Governance", icon: "📜" },
  { p: "/guides", t: "Recommended Club Bylaws", s: "Governance", icon: "📝" },
  { p: "/guides", t: "Statement of Policy", s: "Governance", icon: "🏛️" },
  { p: "/guides", t: "MOU Document", s: "Governance", icon: "🤝" },
  { p: "/guides", t: "Strategic Planning Guide", s: "Planning", icon: "🎯" },
  { p: "/guides", t: "Effective Planning Guide for Clubs", s: "Planning", icon: "📅" },
  { p: "/guides", t: "Membership Application Form", s: "Templates", icon: "📋" },
  { p: "/guides", t: "Sample GM Attendance Sheet", s: "Templates", icon: "✅" },
  { p: "/guides", t: "Sample Agenda Paper", s: "Templates", icon: "🗒️" },
  { p: "/guides", t: "Rotaract Guidebook (District 3292)", s: "Handbook", icon: "📘" },
  { p: "/guides", t: "District Fund (RDG) Grant Criterion", s: "Funding", icon: "💵" },
  { p: "/guides", t: "Rotary-Rotaract Reading Materials (Rota Quiz 2025-26)", s: "Quiz", icon: "🏆" },
  { p: "/guides", t: "Reading Materials for Rota Quiz 25-26", s: "Quiz", icon: "🧠" },
  { p: "/guides", t: "District Directory 25-26", s: "Misc", icon: "📎" },
  { p: "/rkt-quiz", a: "study", t: "Study Deck", s: "RotaQuiz", icon: "📘" },
  { p: "/rkt-quiz", a: "quiz", t: "Quiz Challenge", s: "RotaQuiz", icon: "🎮" },
  { p: "/rkt-quiz", a: "sprint", t: "Acronym Sprint", s: "RotaQuiz", icon: "⚡" }
];