insert into projects (id, club_slug, title, category, date, location, summary, body, cover, gallery, updated)
values
(
  'know-your-teeth-2026',
  'liberty',
  '"Know Your Teeth" — Dental Health Education Session',
  'Dental Camp',
  '2026-03-15',
  'Google Meet (Virtual)',
  'Online dental health session with Reliance and Kantipur Dental Rotaract clubs for World Rotaract Week.',
  'On 15 March 2026, the Rotaract Club of Liberty College co-hosted the online health awareness session "Know Your Teeth" via Google Meet as part of World Rotaract Week celebrations, in collaboration with the Rotaract Club of Reliance College, the Rotaract Club of Kantipur Dental College, and several co-host clubs. Dental health experts Rtr. Dr. Suman Waiba (General Dental Surgeon, Sathi Dental) and Rtr. Dr. Arzoo Gupta (General Dental Surgeon, Padma Dental & Community Hospital) shared professional insights on oral hygiene, preventive care, correct brushing techniques, common dental problems, and long-term oral health, followed by an interactive Q&A. Coordinated by Rtr. Riona Dhungel with 11 club members present, the 1.5-hour session contributed 28 volunteering hours, aligned with SDG 3: Good Health and Well-Being.',
  'media/liberty/dental-session.jpg',
  '["media/liberty/dental-session.jpg"]'::jsonb,
  1750000000000
),
(
  'nepal-japan-dialogue-2026',
  'liberty',
  'High-Level Dialogue on Nepal-Japan Strategic Partnership',
  'Fellowship',
  '2026-04-25',
  'Hotel Radisson',
  'Participation in the Rotary Club of Nagarjun''s strategic Nepal-Japan dialogue with diplomats and MPs.',
  'On 25 April 2026, the Rotaract Club of Liberty College participated in the prestigious High-Level Dialogue on "Strategic Nepal-Japan Partnership in Natural Resources, Innovation, and Economic Development", organized by its parent club, the Rotary Club of Nagarjun, at Hotel Radisson. The program brought together leaders including representatives of Nepal''s National Assembly, Members of the Japanese Parliament and the Japan-Nepal Friendship League, the Ambassador of Japan to Nepal, FNCCI business leaders, and district Rotaract leadership. Sessions covered strengthening bilateral relations, strategic cooperation in natural resources and innovation, technology transfer and economic development, the youth role in international partnerships, and sustainable development through cross-border collaboration. Coordinated by Rtr. Samjhana Sherchan with 3 club members present, the 3-hour dialogue contributed 9 volunteering hours at a total expense of NRs. 770, aligned with SDG 9 and SDG 17.',
  'media/liberty/dental-session.jpg',
  '["media/liberty/dental-session.jpg"]'::jsonb,
  1750000000000
),
(
  'road-safety-symposium-2025',
  'liberty',
  'Rotary Regional Road Safety Symposium',
  'Road Safety',
  '2025-11-08',
  'Nepal House Restaurant, Hattisar, Kathmandu',
  'Regional symposium on road safety policy and youth advocacy with Rotary leaders, WHO Nepal, and experts.',
  'On 8 November 2025, members of the Rotaract Club of Liberty College participated in the Rotary Regional Road Safety Symposium (RID 3292 -- Nepal & Bhutan, Region 1-3) at Nepal House Restaurant, Hattisar, Naxal, Kathmandu. The symposium brought together Rotary International and District 3292 leaders, government authorities, health professionals, and road safety experts -- including the National Road Safety Council and WHO Nepal -- to address road traffic injuries and public safety through dialogue, policy discussion, and knowledge-sharing on road safety policies, emergency response systems, and youth engagement. Panel discussions explored collaborative advocacy involving Rotary, Rotaract, Interact, and community stakeholders. Coordinated by Rtr. Bhawana Kumari Bhatta with 2 club members present, the 3-hour symposium contributed 6 volunteering hours at a total expense of NRs. 250, aligned with SDG 3 and SDG 11.',
  'media/liberty/road-safety-1.jpg',
  '["media/liberty/road-safety-1.jpg", "media/liberty/road-safety-2.jpg", "media/liberty/road-safety-3.jpg"]'::jsonb,
  1750000000000
),
(
  'digital-empowerment-young-minds-2026',
  'liberty',
  'Digital Empowerment for Young Minds',
  'RNLM (TEACH)',
  '2026-03-11',
  'Shree Manohora Lower Secondary School, Duwakot, Bhaktapur',
  'Digital literacy and cyber safety session for 45 students of Grades 6-7 with the Rotaract Club of Sukedhara.',
  'On 11 March 2026, the Rotaract Club of Liberty College, in collaboration with the Rotaract Club of Sukedhara, organized "Digital Empowerment for Young Minds" at Shree Manohora Lower Secondary School, Duwakot-1, Bhaktapur -- a digital literacy session for 45 students of Grades 6 and 7. Facilitated by Rtr. Sushovan Shakya (Sukedhara) and Rtr. Peshal Basnet (Liberty College), the session covered responsible social media use, cyber safety and online protection, identifying misinformation and fake news, and productive use of digital tools, through interactive presentations, quizzes, games, and scenario-based questions, plus a dialogue with school teachers on fostering digital responsibility in classrooms. Directly benefiting 45 students and indirectly reaching 100+ teachers and parents, and coordinated by Rtr. Binda Dahal with 5 club members present, the 1.5-hour session contributed 16 volunteering hours at a total expense of NRs. 1,500, aligned with SDG 4: Quality Education.',
  'media/liberty/digital-1.jpg',
  '["media/liberty/digital-1.jpg", "media/liberty/digital-2.jpg", "media/liberty/digital-3.jpg", "media/liberty/digital-4.jpg", "media/liberty/digital-5.jpg"]'::jsonb,
  1750000000000
),
(
  'leftism-feminism-genz-2026',
  'liberty',
  'Understanding Leftism and Feminism in Gen Z',
  'Women Empowerment',
  '2026-05-16',
  'Liberty College',
  'Speaker session with Georgetown scholar Bimba Panthi on ideology, feminism, and Gen Z digital culture.',
  'On 16 May 2026, the Rotaract Club of Liberty College organized the speaker session "Understanding Leftism and Feminism in Gen Z" at Liberty College premises, jointly with the Rotaract Club of New Road City Kathmandu. Facilitated by distinguished global affairs scholar Mr. Bimba Panthi (BSc in Foreign Service, Georgetown University; writer for Lungri), the session moved beyond social media stereotypes into the structural histories of leftist thought and feminist waves, how Gen Z adopts and reshapes these frameworks, digital platforms as catalysts of youth activism, ideological polarization and echo chambers, and how memes translate serious ideologies for mass consumption. An extended interactive Q&A let students debate polarization, cultural impacts, and political identity, with discussions continuing in small groups long after adjournment. Coordinated by Rtr. Bhawana Kumari Bhatta with 12 members present, the 1.5-hour session contributed 12 volunteering hours at a total expense of NRs. 69.99, aligned with SDG 5.',
  'media/liberty/leftism-feminism.jpg',
  '["media/liberty/leftism-feminism.jpg"]'::jsonb,
  1750000000000
),
(
  'community-cleanup-dashain-tihar-2025',
  'liberty',
  'Community Clean-Up Drive — Dashain & Tihar Season',
  'Cleaning Campaign',
  '2025-09-25',
  'Sachet Marga Tole (Bhaktapur), Global Park (Okhaldhunga), Ghordaura (Dang)',
  'Decentralized festive-season cleanliness drives across three home localities in Bhaktapur, Okhaldhunga, and Dang.',
  'During the Dashain and Tihar festival season of 2025, the Rotaract Club of Liberty College ran a decentralized Local Cleanliness Initiative -- members used their festival holidays in their home villages and localities to lead cleanliness drives in their own neighborhoods. The multi-day campaign covered three locations: Sachet Marga Tole, Kaushaltar, Bhaktapur; Global Park, Okhaldhunga; and Ghordaura, Dang -- spanning urban, hilly, and plains regions of Nepal. Drives focused on streets, lanes, and public spaces, with local residents spontaneously joining at several locations. Coordinated by Rtr. Binda Dahal, Rtr. Bisesh Jung Nepali, and Rtr. Archana Jaiswal, with 4 Rotaractors and 6 other visitors over 15 days, the campaign contributed 15 volunteering hours at a total expense of NRs. 1,640.',
  'media/liberty/cleanup-1.jpg',
  '["media/liberty/cleanup-1.jpg", "media/liberty/cleanup-2.jpg", "media/liberty/cleanup-3.jpg", "media/liberty/cleanup-4.jpg"]'::jsonb,
  1750000000000
),
(
  'bonds-beyond-service-2026',
  'liberty',
  'Bonds Beyond Service — Sharing Love 5.0 Conclusion Gathering',
  'Felicitation / Recognition',
  '2026-04-04',
  'Greenhouse Restaurant',
  'Appreciation gathering closing Sharing Love 5.0 with six partner clubs and tokens of love.',
  'On 4 April 2026, the Rotaract Club of Liberty College organized "Bonds Beyond Service", a special Conclusion and Appreciation Gathering at Greenhouse Restaurant to formally close Sharing Love 5.0, celebrating the collective efforts behind the project and its Beats of Warmth collaboration. Representatives from all collaborating clubs -- RAC New Road City Kathmandu, RAC Reliance College, RAC Kathmandu North East, RAC Bhadgaon, RAC Kathmandu Metropolis, RAC Balkumari, and RAC Liberty College -- reflected on the journey, expressed gratitude, and strengthened fellowship, with each club presented a token of love symbolizing unity and collective service. Coordinated by Rtr. Rahul Khatiwada with 5 club members and 7 Rotaractors present, the one-hour gathering contributed 26 volunteering hours at a total expense of NRs. 2,400.',
  'media/liberty/bonds-1.jpg',
  '["media/liberty/bonds-1.jpg", "media/liberty/bonds-2.jpg", "media/liberty/bonds-3.jpg", "media/liberty/bonds-4.jpg"]'::jsonb,
  1750000000000
),
(
  'traffic-office-equipment-handover-2026',
  'liberty',
  'Equipment Handover to Kathmandu Valley Traffic Office',
  'Collaboration / Partnership / Volunteering',
  '2026-01-30',
  'Everest Hotel, Kathmandu',
  'Computer and printer donated to the Traffic Office with Rotary Nagarjun and Nepal Traffic Police.',
  'On 30 January 2026, on the occasion of the 22nd Charter Day of the Rotary Club of Nagarjun, a computer and printer were officially donated to the Kathmandu Valley Traffic Office to replace equipment damaged during recent public unrest, restoring operational efficiency and public service delivery. The handover at Everest Hotel, Kathmandu, was carried out in collaboration with the Nepal Traffic Police and the Rotaract Club of Liberty College, in the presence of District Governor Rtn. Binod Koirala, district officials, and Rotary members. Coordinated by Rtr. Riona Dhungel with 3 club members and 5 Rotaractors present, the 2-hour program contributed 72 volunteering hours at a total expense of NRs. 349.96, aligned with SDG 11 and SDG 16.',
  'media/liberty/dental-session.jpg',
  '["media/liberty/dental-session.jpg"]'::jsonb,
  1750000000000
)
on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  date = excluded.date,
  location = excluded.location,
  summary = excluded.summary,
  body = excluded.body,
  cover = excluded.cover,
  gallery = excluded.gallery,
  updated = excluded.updated;
