insert into projects (id, club_slug, title, category, date, location, summary, body, cover, gallery, updated)
values
(
  'eye-camp-balkumari-school-2025',
  'sukedhara',
  'Free Eye Camp at Shree Balkumari School',
  'Health Camp',
  '2025-05-30',
  'Shree Balkumari School',
  '350 students screened and 13 treated with RAC Liberty College, RAC Damak, RC Nagarjun, and Everest Eye Care Center.',
  'The Rotaract Club of Sukedhara hosted a Free Eye Camp at Shree Balkumari School on 30 May 2025, in collaboration with RAC Liberty College and RAC Damak, with support from RC Nagarjun. Led by Everest Eye Care Center with Dr. Prabin Chhetri, the camp provided free eye screenings and diagnoses: 350 students screened, of which 13 were diagnosed with various eye deficiencies and treated accordingly, with a team of five volunteers and one medical staff. The initiative also opened discussions on further healthcare collaborations and long-term sustainability of similar programs. Coordinated by Rtr. Rajay Bajracharya with 3 club members and 2 Rotaractors present, the 4-hour camp contributed 3 volunteering hours at a total expense of NRs. 10,000, aligned with SDG 3.',
  'media/sukedhara/eyecamp-1.jpg',
  '["media/sukedhara/eyecamp-1.jpg", "media/sukedhara/eyecamp-2.jpg", "media/sukedhara/eyecamp-3.jpg", "media/sukedhara/eyecamp-4.jpg", "media/sukedhara/eyecamp-5.jpg", "media/sukedhara/eyecamp-6.jpg"]'::jsonb,
  1750000000000
),
(
  'teach-feel-deal-heal-2025',
  'sukedhara',
  'Project TEACH: Feel It, Deal It, Heal It — Adolescents and Emotions',
  'RNLM (TEACH)',
  '2025-05-19',
  'Trikon Public Secondary School',
  'Zone-7-wide emotional intelligence session for adolescents led by Rtn. Osha Shrestha with role-play and emotion cards.',
  'The Rotaract Club of Sukedhara hosted Project TEACH "Feel It, Deal It, Heal It -- Adolescents and Emotions" on 19 May 2025 at Trikon Public Secondary School, jointly with all Zone 7 clubs: RAC Kathmandu West, RAC New Road City Kathmandu, RAC Tripureswor, RAC Liberty College, RAC Sankhu, RAC Baneshwor, and RAC Balkumari. Rtn. Osha Shrestha guided students through an interactive session on understanding, managing, and healing emotions -- with breathing exercises, real-life storytelling, fun role-playing, emotion cards, and safe sharing spaces -- while volunteers ensured each child received personalized attention. Coordinated by Prasanna Shakya, with 10 Rotaractors across the joint clubs, the 2-hour session contributed 20 volunteering hours at a total expense of NRs. 95.98.',
  'media/sukedhara/teach-1.jpg',
  '["media/sukedhara/teach-1.jpg", "media/sukedhara/teach-2.jpg", "media/sukedhara/teach-3.jpg", "media/sukedhara/teach-4.jpg", "media/sukedhara/teach-5.jpg", "media/sukedhara/teach-chart.png"]'::jsonb,
  1750000000000
),
(
  'club-cots-2025',
  'sukedhara',
  'Club COTS',
  'Training / Workshops',
  '2025-05-06',
  'Google Meet (Virtual)',
  'Club Officer Training Seminar on roles, governance, and public speaking with ADLT Rtr. Ruchin Khadka.',
  'The Rotaract Club of Sukedhara conducted a virtual Club COTS (Club Officer Training Seminar) session on 6 May 2025 via Google Meet, facilitated by Rtr. Ruchin Khadka, Assistant District Leadership Trainer from the Rotaract Club of Kathmandu Metro, and hosted by Rtr. Mohit Muni Bajracharya as Master of Ceremony. New members and incoming-year designees learned the roles and responsibilities of a Rotaractor and club director, club governance and what not to do while representing as a Rotaractor, while building rapport and practicing public speaking -- with thought-provoking questions from Rtr. Sushovan Shakya and Rtr. Rajay Bajracharya. A virtual certificate of appreciation honored the facilitator. With 11 Sukedhara members and 1 Metro guest (12 Rotaractors), the 1.25-hour session contributed 16 volunteering hours.',
  'media/sukedhara/cots-1.png',
  '["media/sukedhara/cots-1.png", "media/sukedhara/cots-2.png", "media/sukedhara/cots-3.png", "media/sukedhara/cots-4.png", "media/sukedhara/cots-5.png"]'::jsonb,
  1750000000000
),
(
  'library-setup-nakkhu-2025',
  'sukedhara',
  'Library Set-Up at The Orphans Home, Nakkhu',
  'Donation',
  '2025-03-02',
  'The Orphans Home, Nakkhu, Lalitpur',
  '300 books worth Rs. 30,000+ donated with Balkumari, Liberty College, and Pashupati Law Campus.',
  'The Rotaract Club of Sukedhara, jointly with RAC Balkumari, RAC Liberty College, and RAC Pashupati Nepal Law Campus, set up a library at The Orphans Home, Nakkhu, Lalitpur, on 2 March 2025. With generous support from fellow Rotaractors, 300 books valued over Rs. 30,000 were collected and donated, giving children access to educational resources and recreational reading -- received with joy and excitement, alongside a fellowship with the children. Coordinated by Rtr. Rajay Bajracharya with Rtr. Mohit Muni Bajracharya and Praman Shrestha and 13 Rotaractors present, the 1 hour 45 minute program contributed 29 volunteering hours, aligned with SDG 4.',
  'media/sukedhara/library.jpg',
  '["media/sukedhara/library.jpg"]'::jsonb,
  1750000000000
),
(
  'digital-privacy-security-2025',
  'sukedhara',
  'Digital Privacy Security Awareness Session',
  'Training / Workshops',
  '2025-02-23',
  'Google Meet (Virtual)',
  'Cybersecurity session on passwords, 2FA, encryption, and digital rights with 8 co-host clubs and 75 Rotaractors.',
  'The Rotaract Club of Sukedhara and the Rotaract Club of Liberty College hosted the Digital Privacy Security Awareness Session on 23 February 2025 via Google Meet, co-hosted by RAC Reliance College, RAC Balaju, RAC Kathmandu Metropolis, RAC Kathmandu North East, RAC Bhadgaon, RAC Thames, and RAC Kathmandu West. Facilitated by Mr. Sushovan Shakya, the session covered digital threats (hacking, phishing, data breaches), secure password management, two-factor authentication, data encryption, safe browsing, cybersecurity laws, digital rights, and ethical online conduct. Coordinated by Sushovan Shakya with 8 club members present, 75 Rotaractors took part over 2 hours, contributing 21 volunteering hours.',
  'media/sukedhara/privacy-1.jpg',
  '["media/sukedhara/privacy-1.jpg", "media/sukedhara/privacy-2.jpg", "media/sukedhara/privacy-3.jpg", "media/sukedhara/privacy-4.jpg", "media/sukedhara/privacy-5.jpg", "media/sukedhara/privacy-6.jpg"]'::jsonb,
  1750000000000
),
(
  'gift-of-hope-2-2024',
  'sukedhara',
  'Gift of Hope 2.0 — Stationery Donation at Shree Hira Devi School, Melamchi',
  'Signature Project',
  '2024-08-23',
  'Shree Hira Devi School, Melamchi',
  'District-grant signature project: 32 bags, 96 copies, 64 pens for students with Rotary Nagarjun and Asha Foundation.',
  'The Rotaract Club of Sukedhara and the Rotary Club of Nagarjun, under Rotary District 3292 district grant DG 2023/24-108, organized "Gift of Hope 2.0" on 23 August 2024 at Shree Hira Devi School, Melamchi. Led by President Rtr. Rajay Bajracharya with the Asha Foundation, 32 bags, 96 copies, and 64 pens were donated to students -- supplying essential resources, fostering a positive learning environment, and bridging educational gaps for underprivileged children. Coordinated by Prabhu Ram Sapkota with 5 club members and 32 other visitors present, the 3-hour signature project contributed 78 volunteering hours at a total expense of NRs. 18,800, aligned with SDG 4.',
  'media/sukedhara/gifthope-1.jpg',
  '["media/sukedhara/gifthope-1.jpg", "media/sukedhara/gifthope-2.jpg", "media/sukedhara/gifthope-3.jpg"]'::jsonb,
  1750000000000
),
(
  'reusable-menstrual-pad-melamchi-2025',
  'sukedhara',
  'Making and Distribution of Reusable Menstrual Pads',
  'District Event',
  '2025-04-05',
  'Shree Sitaldevi Secondary School, Sindhupalchok / Melamchi',
  '3-day MHM training for 32 schoolgirls: orientation, kits, and pad-making, backed by District Grant and Rotary Nagarjun.',
  'The Rotaract Club of Sukedhara, supported by the Rotary Club of Nagarjun and a District Grant (NPR 2,33,000 total support), ran a 3-day menstrual hygiene management program on 5-7 April 2025 (filed with fieldwork at Shree Hira Devi Basic School and Shree Sitaldevi Secondary School, Sindhupalchok/Melamchi). Day-wise: orientation on menstruation biology and womanhood (31 students), hygiene education and myth-busting (32 students), and hands-on reusable pad-making training (32 students). Ms. Prajita Subedhi led the WASH and MHM orientation; Mr. Chandra Bhakta Adhikari covered oral hygiene; teachers and parents were oriented on MHM importance and the Chhaupadi ban; MHM kits (4 holders, 3 napkins, antibacterial soap, 2 undergarments, 2 ziplock bags, school bag) were distributed to 32 girls of classes 8-10 with a knowledge survey. Trainer Mr. Prabhu Ram Sapkota led pad-making in Melamchi Municipality with Ward 10 Chair Mr. Amrit Khanal attending. Coordinated by Rtr. Chandra Bhakta Adhikari and Prabhu Ram Sapkota with 5 members and 12 visitors over 3 days, the program contributed 245 volunteering hours at a total expense of NRs. 290,000, aligned with SDG 3 and SDG 4.',
  'media/sukedhara/mhm-1.jpg',
  '["media/sukedhara/mhm-1.jpg", "media/sukedhara/mhm-2.jpg", "media/sukedhara/mhm-3.jpg", "media/sukedhara/mhm-4.jpg", "media/sukedhara/mhm-topics.png", "media/sukedhara/mhm-focus.png"]'::jsonb,
  1750000000000
),
(
  'changing-narrative-suicide-2024',
  'sukedhara',
  'Changing the Narrative on Suicide',
  'International Online Exchange',
  '2024-09-10',
  'Google Meet (Virtual)',
  'World Suicide Prevention Day webinar with psychiatrist Dr. Purshotam Singh and letterhead exchange across clubs.',
  'On World Suicide Prevention Day, 10 September 2024, the Rotaract Club of Sukedhara hosted the virtual session "Changing the Narrative on Suicide" via Google Meet, jointly with RAC United Birgunj and RAC Sunsari. Chief speaker Dr. Purshotam Singh, psychiatrist from India, delivered a 30-minute presentation on what suicide is, why and how it happens, identification and prevention, and global statistics; engaging questions from Rtr. Rajay Bajracharya and Rtr. Mohit Muni Bajracharya enriched the dialogue. A virtual token of love honored Dr. Singh, and letterheads were exchanged among participating clubs for continued collaboration on mental health awareness. Coordinated by Mohit Muni Bajracharya with 7 club members and 55 Rotaractors present, the one-hour session contributed 55 volunteering hours, aligned with SDG 3.',
  'media/sukedhara/suicide-1.png',
  '["media/sukedhara/suicide-1.png", "media/sukedhara/suicide-2.png", "media/sukedhara/suicide-3.png", "media/sukedhara/suicide-4.png", "media/sukedhara/suicide-5.png", "media/sukedhara/suicide-6.png"]'::jsonb,
  1750000000000
),
(
  'esrag-wash-balkumari-school-2025',
  'sukedhara',
  'ESRAG Grant Project — Waste Segregation & WASH at Balkumari School',
  'Sanitation',
  '2025-06-29',
  'Shree Balkumari School, Sunakothi-27, Lalitpur',
  'US$500 ESRAG grant: waste segregation and WASH training for Classes 3-5 plus 32 bins with Lalitpur Metro support.',
  'The Rotaract Club of Sukedhara conducted the Waste Segregation and WASH Awareness Program on 29 June 2025 at Shree Balkumari Secondary School, Sunakothi-27, Lalitpur, supported by the ESRAG Global Board (US $500 grant) with the school administration and Lalitpur Metropolitan City. Targeting Classes 3, 4, and 5 after a needs assessment, activities included orientation on segregating biodegradable, recyclable, and non-recyclable waste and WASH principles; practical training by Er. Rahul Ranabhat (civil engineer, MSc Environmental Engineering) with relatable examples on disposal, composting, and personal hygiene; engagement with teachers and parents; and distribution of 12 large (green/red) and 20 small blue bins for sustained segregation. Coordinated by Sushovan Shakya with 6 club members, 5 Rotaractors, and 18 other visitors over 8 hours, the grant project contributed 19.97 volunteering hours at a total expense of NRs. 66,000, aligned with SDG 17 and Rotary''s environment focus.',
  'media/sukedhara/esrag-1.jpg',
  '["media/sukedhara/esrag-1.jpg", "media/sukedhara/esrag-2.jpg", "media/sukedhara/esrag-3.jpg", "media/sukedhara/esrag-4.jpg", "media/sukedhara/esrag-5.jpg"]'::jsonb,
  1750000000000
)
on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  date = excluded.date,
  location = excluded.location,
  summary = excluded.summary,
  body = excluded.body,
  cover = excluded.cover,
  gallery = excluded.gallery,
  updated = excluded.updated;
